default:
  cache:
    - key: 
        files:
          - package-lock.json
      paths:
        - node_modules/
    - key: 
        files: 
          - composer.lock
      paths:
        - .composer-cache/
        - vendor/
        - public/